/// <summary>
/// A simple class that is used to hold the raw data for the application. All mistakes
/// are saved as an integer for the associated values in the class. Upon class creation
/// all values are set to 0. The add_H_Stat and add_K_Stat functions then take a specific
/// input and increment the associated value by 1. The class is then re-serialized by the 
/// SaveSystem class.
/// </summary>

[System.Serializable]
public class StatisticalData
{
    #region hiragana mistakes
    public int h_A;
    public int h_I;
    public int h_U;
    public int h_E;
    public int h_O;
    public int h_Ka;
    public int h_Ki;
    public int h_Ku;
    public int h_Ke;
    public int h_Ko;
    public int h_Sa;
    public int h_Shi;
    public int h_Su;
    public int h_Se;
    public int h_So;
    public int h_Ta;
    public int h_Chi;
    public int h_Tsu;
    public int h_Te;
    public int h_To;
    public int h_Na;
    public int h_Ni;
    public int h_Nu;
    public int h_Ne;
    public int h_No;
    public int h_Ha;
    public int h_Hi;
    public int h_Fu;
    public int h_He;
    public int h_Ho;
    public int h_Ma;
    public int h_Mi;
    public int h_Mu;
    public int h_Me;
    public int h_Mo;
    public int h_Ya;
    public int h_Yu;
    public int h_Yo;
    public int h_Ra;
    public int h_Ri;
    public int h_Ru;
    public int h_Re;
    public int h_Ro;
    public int h_Wa;
    public int h_Wo;
    public int h_N;
    public int h_Ga;
    public int h_Gi;
    public int h_Gu;
    public int h_Ge;
    public int h_Go;
    public int h_Za;
    public int h_Ji_1;
    public int h_Ji_2;
    public int h_Zu_1;
    public int h_Zu_2;
    public int h_Ze;
    public int h_Zo;
    public int h_Da;
    public int h_De;
    public int h_Do;
    public int h_Ba;
    public int h_Bi;
    public int h_Bu;
    public int h_Be;
    public int h_Bo;
    public int h_Pa;
    public int h_Pi;
    public int h_Pu;
    public int h_Pe;
    public int h_Po;
    #endregion

    #region Katakana mistakes
    public int k_A;
    public int k_I;
    public int k_U;
    public int k_E;
    public int k_O;
    public int k_Ka;
    public int k_Ki;
    public int k_Ku;
    public int k_Ke;
    public int k_Ko;
    public int k_Sa;
    public int k_Shi;
    public int k_Su;
    public int k_Se;
    public int k_So;
    public int k_Ta;
    public int k_Chi;
    public int k_Tsu;
    public int k_Te;
    public int k_To;
    public int k_Na;
    public int k_Ni;
    public int k_Nu;
    public int k_Ne;
    public int k_No;
    public int k_Ha;
    public int k_Hi;
    public int k_Fu;
    public int k_He;
    public int k_Ho;
    public int k_Ma;
    public int k_Mi;
    public int k_Mu;
    public int k_Me;
    public int k_Mo;
    public int k_Ya;
    public int k_Yu;
    public int k_Yo;
    public int k_Ra;
    public int k_Ri;
    public int k_Ru;
    public int k_Re;
    public int k_Ro;
    public int k_Wa;
    public int k_Wo;
    public int k_N;
    public int k_Ga;
    public int k_Gi;
    public int k_Gu;
    public int k_Ge;
    public int k_Go;
    public int k_Za;
    public int k_Ji_1;
    public int k_Ji_2;
    public int k_Zu_1;
    public int k_Zu_2;
    public int k_Ze;
    public int k_Zo;
    public int k_Da;
    public int k_De;
    public int k_Do;
    public int k_Ba;
    public int k_Bi;
    public int k_Bu;
    public int k_Be;
    public int k_Bo;
    public int k_Pa;
    public int k_Pi;
    public int k_Pu;
    public int k_Pe;
    public int k_Po;
    #endregion

    public void add_H_Stat(string s) {
        switch (s) {
            case "A": h_A++; break;
            case "I": h_I++; break;
            case "U": h_U++; break;
            case "E": h_E++; break;
            case "O": h_O++; break;
            case "Ka": h_Ka++; break;
            case "Ki": h_Ki++; break;
            case "Ku": h_Ku++; break;
            case "Ke": h_Ke++; break;
            case "Ko": h_Ko++; break;
            case "Sa": h_Sa++; break;
            case "Shi": h_Shi++; break;
            case "Su": h_Su++; break;
            case "Se": h_Se++; break;
            case "So": h_So++; break;
            case "Ta": h_Ta++; break;
            case "Chi": h_Chi++; break;
            case "Tsu": h_Tsu++; break;
            case "Te": h_Te++; break;
            case "To": h_To++; break;
            case "Na": h_Na++; break;
            case "Ni": h_Ni++; break;
            case "Nu": h_Nu++; break;
            case "Ne": h_Ne++; break;
            case "No": h_No++; break;
            case "Ha": h_Ha++; break;
            case "Hi": h_Hi++; break;
            case "Fu": h_Fu++; break;
            case "He": h_He++; break;
            case "Ho": h_Ho++; break;
            case "Ma": h_Ma++; break;
            case "Mi": h_Mi++; break;
            case "Mu": h_Mu++; break;
            case "Me": h_Me++; break;
            case "Mo": h_Mo++; break;
            case "Ya": h_Ya++; break;
            case "Yu": h_Yu++; break;
            case "Yo": h_Yo++; break;
            case "Ra": h_Ra++; break;
            case "Ri": h_Ri++; break;
            case "Ru": h_Ru++; break;
            case "Re": h_Re++; break;
            case "Ro": h_Ro++; break;
            case "Wa": h_Wa++; break;
            case "Wo": h_Wo++; break;
            case "N": h_N++; break;
            case "Ga": h_Ga++; break;
            case "Gi": h_Gi++; break;
            case "Gu": h_Gu++; break;
            case "Ge": h_Ge++; break;
            case "Go": h_Go++; break;
            case "Za": h_Za++; break;
            case "Ji_1": h_Ji_1++; break;
            case "Ji_2": h_Ji_2++; break;
            case "Zu_1": h_Zu_1++; break;
            case "Zu_2": h_Zu_2++; break;
            case "Ze": h_Ze++; break;
            case "Zo": h_Zo++; break;
            case "Da": h_Da++; break;
            case "De": h_De++; break;
            case "Do": h_Do++; break;
            case "Ba": h_Ba++; break;
            case "Bi": h_Bi++; break;
            case "Bu": h_Bu++; break;
            case "Be": h_Be++; break;
            case "Bo": h_Bo++; break;
            case "Pa": h_Pa++; break;
            case "Pi": h_Pi++; break;
            case "Pu": h_Pu++; break;
            case "Pe": h_Pe++; break;
            case "Po": h_Po++; break;
        }
    }

    public void add_K_Stat(string s) {
        switch (s) {
            case "A": k_A++; break;
            case "I": k_I++; break;
            case "U": k_U++; break;
            case "E": k_E++; break;
            case "O": k_O++; break;
            case "Ka": k_Ka++; break;
            case "Ki": k_Ki++; break;
            case "Ku": k_Ku++; break;
            case "Ke": k_Ke++; break;
            case "Ko": k_Ko++; break;
            case "Sa": k_Sa++; break;
            case "Shi": k_Shi++; break;
            case "Su": k_Su++; break;
            case "Se": k_Se++; break;
            case "So": k_So++; break;
            case "Ta": k_Ta++; break;
            case "Chi": k_Chi++; break;
            case "Tsu": k_Tsu++; break;
            case "Te": k_Te++; break;
            case "To": k_To++; break;
            case "Na": k_Na++; break;
            case "Ni": k_Ni++; break;
            case "Nu": k_Nu++; break;
            case "Ne": k_Ne++; break;
            case "No": k_No++; break;
            case "Ha": k_Ha++; break;
            case "Hi": k_Hi++; break;
            case "Fu": k_Fu++; break;
            case "He": k_He++; break;
            case "Ho": k_Ho++; break;
            case "Ma": k_Ma++; break;
            case "Mi": k_Mi++; break;
            case "Mu": k_Mu++; break;
            case "Me": k_Me++; break;
            case "Mo": k_Mo++; break;
            case "Ya": k_Ya++; break;
            case "Yu": k_Yu++; break;
            case "Yo": k_Yo++; break;
            case "Ra": k_Ra++; break;
            case "Ri": k_Ri++; break;
            case "Ru": k_Ru++; break;
            case "Re": k_Re++; break;
            case "Ro": k_Ro++; break;
            case "Wa": k_Wa++; break;
            case "Wo": k_Wo++; break;
            case "N": k_N++; break;
            case "Ga": k_Ga++; break;
            case "Gi": k_Gi++; break;
            case "Gu": k_Gu++; break;
            case "Ge": k_Ge++; break;
            case "Go": k_Go++; break;
            case "Za": k_Za++; break;
            case "Ji_1": k_Ji_1++; break;
            case "Ji_2": k_Ji_2++; break;
            case "Zu_1": k_Zu_1++; break;
            case "Zu_2": k_Zu_2++; break;
            case "Ze": k_Ze++; break;
            case "Zo": k_Zo++; break;
            case "Da": k_Da++; break;
            case "De": k_De++; break;
            case "Do": k_Do++; break;
            case "Ba": k_Ba++; break;
            case "Bi": k_Bi++; break;
            case "Bu": k_Bu++; break;
            case "Be": k_Be++; break;
            case "Bo": k_Bo++; break;
            case "Pa": k_Pa++; break;
            case "Pi": k_Pi++; break;
            case "Pu": k_Pu++; break;
            case "Pe": k_Pe++; break;
            case "Po": k_Po++; break;
        }
    }

    public StatisticalData() {
        h_A = 0; 
        h_I = 0; 
        h_U = 0; 
        h_E = 0; 
        h_O = 0; 
        h_Ka = 0;
        h_Ki = 0;
        h_Ku = 0;
        h_Ke = 0;
        h_Ko = 0;
        h_Sa = 0;
        h_Shi = 0;
        h_Su = 0;
        h_Se = 0;
        h_So = 0;
        h_Ta = 0;
        h_Chi = 0;
        h_Tsu = 0;
        h_Te = 0;
        h_To = 0;
        h_Na = 0;
        h_Ni = 0;
        h_Nu = 0;
        h_Ne = 0;
        h_No = 0;
        h_Ha = 0;
        h_Hi = 0;
        h_Fu = 0;
        h_He = 0;
        h_Ho = 0;
        h_Ma = 0;
        h_Mi = 0;
        h_Mu = 0;
        h_Me = 0;
        h_Mo = 0;
        h_Ya = 0;
        h_Yu = 0;
        h_Yo = 0;
        h_Ra = 0;
        h_Ri = 0;
        h_Ru = 0;
        h_Re = 0;
        h_Ro = 0;
        h_Wa = 0;
        h_Wo = 0;
        h_N = 0;
        h_Ga = 0; 
        h_Gi = 0; 
        h_Gu = 0; 
        h_Ge = 0; 
        h_Go = 0; 
        h_Za = 0; 
        h_Ji_1 = 0;
        h_Ji_2 = 0;
        h_Zu_1 = 0;
        h_Zu_2 = 0;
        h_Ze = 0;  
        h_Zo = 0;  
        h_Da = 0;  
        h_De = 0;  
        h_Do = 0;  
        h_Ba = 0;  
        h_Bi = 0;  
        h_Bu = 0;  
        h_Be = 0;  
        h_Bo = 0;  
        h_Pa = 0;  
        h_Pi = 0;  
        h_Pu = 0;  
        h_Pe = 0;  
        h_Po = 0; 

        k_A = 0; 
        k_I = 0; 
        k_U = 0; 
        k_E = 0; 
        k_O = 0; 
        k_Ka = 0;
        k_Ki = 0;
        k_Ku = 0;
        k_Ke = 0;
        k_Ko = 0;
        k_Sa = 0;
        k_Shi = 0;
        k_Su = 0;
        k_Se = 0;
        k_So = 0;
        k_Ta = 0;
        k_Chi = 0;
        k_Tsu = 0;
        k_Te = 0;
        k_To = 0;
        k_Na = 0;
        k_Ni = 0;
        k_Nu = 0;
        k_Ne = 0;
        k_No = 0;
        k_Ha = 0;
        k_Hi = 0;
        k_Fu = 0;
        k_He = 0;
        k_Ho = 0;
        k_Ma = 0;
        k_Mi = 0;
        k_Mu = 0;
        k_Me = 0;
        k_Mo = 0;
        k_Ya = 0;
        k_Yu = 0;
        k_Yo = 0;
        k_Ra = 0;
        k_Ri = 0;
        k_Ru = 0;
        k_Re = 0;
        k_Ro = 0;
        k_Wa = 0;
        k_Wo = 0;
        k_N = 0;
        k_Ga = 0; 
        k_Gi = 0; 
        k_Gu = 0; 
        k_Ge = 0; 
        k_Go = 0; 
        k_Za = 0; 
        k_Ji_1 = 0;
        k_Ji_2 = 0;
        k_Zu_1 = 0;
        k_Zu_2 = 0;
        k_Ze = 0;  
        k_Zo = 0;  
        k_Da = 0;  
        k_De = 0;  
        k_Do = 0;  
        k_Ba = 0;  
        k_Bi = 0;  
        k_Bu = 0;  
        k_Be = 0;  
        k_Bo = 0;  
        k_Pa = 0;  
        k_Pi = 0;  
        k_Pu = 0;  
        k_Pe = 0;  
        k_Po = 0; 
    }
}
